# Generated by Django 3.2.16 on 2022-11-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Order',
        ),
    ]
