# Generated by Django 3.2.16 on 2022-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_rename_request_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='Company', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='vat_no',
            field=models.IntegerField(default='000000'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
