# Generated by Django 3.2.16 on 2022-11-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0003_auto_20221115_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_partner',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(2, 'Customer'), (3, 'Partner')], default=2, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='vat_no',
            field=models.CharField(default='000000-0000', max_length=50),
        ),
    ]
