# Generated by Django 3.2.16 on 2022-11-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0007_candidate_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='summary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='startdate',
            field=models.DateField(),
        ),
    ]
