# Generated by Django 3.2.16 on 2022-11-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0008_auto_20221125_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
