# Generated by Django 3.2.16 on 2022-11-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0009_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='summary',
            field=models.CharField(max_length=200),
        ),
    ]
