# Generated by Django 3.2.16 on 2022-11-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0010_alter_candidate_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vat_no',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
